### ISSUE TITLE
Sublime Text 2 Support

### ISSUE THREAD

**Issue by bbeckford** [SublimeText/OpenDefaultApplication#1]
Love the idea, any chance of porting to Sublime Text 2?

Thanks!

**Comment by FichteFoll** [comment]
Overall, it looks like the code is mostly ST2-compatible.

~~The only potentially offending line is [here](https://github.com/SublimeText/OpenDefaultApplication/blob/d8ef1190652dafd03b1f2c8a1ca2b4179ea5d835/OpenDefault.py#L36) because window commands might be instantiated before the API has loaded, but I never explicitly tested that.~~ That would only be an issue on ST3 anyway.

**Comment by bbeckford** [comment]
Hmm I'm not sure how to get it working with ST2, I tried putting it in my packages folder but didn't get anywhere - more research required!

**Comment by braver** [comment]
3.0 is out, so this isn’t really relevant anymore.
